package org.overbeck.weather

case class DeviceData(dateutc: Long,
                      baromabsin: Double,
                      baromrelin: Double,
                      battout: Int,
                      batt1: Option[Int] = None,
                      batt2: Option[Int] = None,
                      batt3: Option[Int] = None,
                      batt4: Option[Int] = None,
                      batt5: Option[Int] = None,
                      batt6: Option[Int] = None,
                      batt7: Option[Int] = None,
                      batt8: Option[Int] = None,
                      batt9: Option[Int] = None,
                      batt10: Option[Int] = None,
                      co2: Option[Double] = None,
                      dailyrainin: Double,
                      date: String,
                      dewPoint: Double,
                      dewPointin: Double,
                      eventrainin: Double,
                      feelsLike: Double,
                      feelsLikein: Double,
                      hourlyrainin: Double,
                      humidity: Int,
                      humidityin: Int,
                      humidity1: Option[Int] = None,
                      humidity2: Option[Int] = None,
                      humidity3: Option[Int] = None,
                      humidity4: Option[Int] = None,
                      humidity5: Option[Int] = None,
                      humidity6: Option[Int] = None,
                      humidity7: Option[Int] = None,
                      humidity8: Option[Int] = None,
                      humidity9: Option[Int] = None,
                      humidity10: Option[Int] = None,
                      lastRain: String,
                      loc: String,
                      maxdailygust: Double,
                      monthlyrainin: Double,
                      pm25: Option[Int] = None,
                      pm25_24h: Option[Float] = None,
//                      relay1: Option[Int],
//                      relay2: Option[Int],
//                      relay3: Option[Int],
//                      relay4: Option[Int],
//                      relay5: Option[Int],
//                      relay6: Option[Int],
//                      relay7: Option[Int],
//                      relay8: Option[Int],
//                      relay9: Option[Int],
//                      relay10: Option[Int],
                      solarradiation: Double,
                      tempf: Double,
                      tempinf: Int,
//                      temp1f: Option[Float],
//                      temp2f: Option[Float],
//                      temp3f: Option[Float],
//                      temp4f: Option[Float],
//                      temp5f: Option[Float],
//                      temp6f: Option[Float],
//                      temp7f: Option[Float],
//                      temp8f: Option[Float],
//                      temp9f: Option[Float],
//                      temp10f: Option[Float],
                      totalrainin: Double,
                      // uv should be Int but see https://github.com/lrosenman/ambient/blob/19dbc288eb9acd7baa4205eab7adeb81a2b555c5/ambient.go#L92
                      uv: Double,

                      weeklyrainin: Double,
                      winddir: Int,
                      winddir_avg2m: Option[Int] = None,
                      winddir_avg10m: Option[Int] = None,
                      windgustdir: Option[Int] = None,
                      windgustmph: Int,
                      windspeedmph: Int,
                      windspdmph_avg2m: Option[Float] = None,
                      windspdmph_avg10m: Option[Float] = None,
                      yearlyrainin: Option[Float] = None
)


object DeviceData {
  implicit val rw: OptionPickler.ReadWriter[DeviceData] = OptionPickler.macroRW
}

